FROM python:3.10
LABEL authors="avar"
ENV PYTHONUNBUFFERED 1

RUN apt-get update  && apt-get upgrade -y

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
RUN pip install --upgrade pip 
RUN pip install oss2 tos httpx[http2] requests redis pillow

