FROM nvidia/cuda:12.6.2-cudnn-runtime-ubuntu22.04
LABEL authors="aiuni"
ENV PYTHONUNBUFFERED 1
SHELL ["/bin/bash", "-c"]
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive
RUN apt update  && apt upgrade -y && apt install -y  tzdata   python3-pip

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
RUN pip install --upgrade pip
RUN pip3 install oss2 tos httpx[http2] requests redis pillow
