FROM python:3.12
LABEL authors="avar"
SHELL ["/bin/bash", "-c"]
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1
RUN apt-get update  && apt-get upgrade -y && apt install -y  tzdata

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
