FROM ubuntu:latest
LABEL authors="tiyee"
ENV PYTHONUNBUFFERED 1

RUN apt update  && apt upgrade -y && apt install -y  tzdata 

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
RUN /usr/bin/pip3 install --upgrade pip 
RUN /usr/bin/pip3 install oss2 tos httpx[http2] requests redis pillow
