FROM python:3.12
LABEL authors="tiyee"
SHELL ["/bin/bash", "-c"]
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1
RUN apt-get update  && apt-get upgrade -y && apt install -y  tzdata  rustc cargo

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
RUN pip3 install --upgrade pip 
RUN pip3 install oss2  httpx[http2] requests redis pillow uvicorn fastapi sqlalchemy pydantic==2.10.6 pydantic-core==2.27.2
