FROM ubuntu:latest
LABEL authors="tiyee"
ENV PYTHONUNBUFFERED 1
SHELL ["/bin/bash", "-c"]
RUN apt update  && apt upgrade -y && apt install -y  tzdata  python3-full python3-pip

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
RUN  /usr/bin/pip3  install  pip --upgrade --break-system-packages
RUN pip3 install oss2 tos httpx[http2] requests redis pillow --break-system-packages
