FROM python:3.12
LABEL authors="avar"
SHELL ["/bin/bash", "-c"]
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1
RUN apt-get update  && apt-get upgrade -y && apt install -y  tzdata

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone

WORKDIR /venv
# 创建虚拟环境
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"
ENV VIRTUAL_ENV=/venv

# 设置pip镜像源（在虚拟环境中）
# RUN /venv/bin/pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN /venv/bin/pip install --upgrade pip
RUN source /venv/bin/activate
# 在虚拟环境中安装Python包
RUN pip install oss2 tos httpx[http2] requests redis pillow "pydantic>=2.0.0" gunicorn uvicorn[standard] playwright
