FROM python:3.10
LABEL authors="avar"
ENV PYTHONUNBUFFERED 1
SHELL ["/bin/bash", "-c"]
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive
RUN apt-get update  && apt-get upgrade -y && apt install -y  tzdata

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
RUN pip3 install --upgrade pip 
RUN pip3 install oss2 tos httpx[http2] requests redis pillow
